### ISSUE TITLE
Missleading "Returning Focus" example

### ISSUE THREAD

**Issue by pascalduez** [discord/focus-layers#7]
Hi,

the Readme "Returning Focus" example is not working, the `containerRef` passed to the hook is empty and not assigned to an element. Also I guess [it's now outdated](https://github.com/discord/focus-layers/commit/3207e2fdd0d16b8094ce58397ca4d166072d0a92).

So what would be the current "proper" way to return focus on a different element than the triggering one?

Thanks!

**Comment by faultyserver** [comment]
I ended up removing this behavior just because I couldn't get the ref setup working correctly, but meant to re-add after finishing up the rest of the package.

I think I can re-add this quickly, so I'll get to that now!
